using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using NesLifter.Core;
using NesLifter.Core.Boards;

namespace NesLifter.Lifting
{
    public sealed class Lifter
    {
        private readonly NesRom _rom;
        private readonly AnalysisResult _model;
        private readonly string _nsName;
        private readonly CartMapping _mapping;
        private readonly IBoard _board;

        private readonly Dictionary<ushort, bool> _labels = new Dictionary<ushort, bool>();
        private readonly List<ushort> _emitted = new List<ushort>();
        private readonly List<ushort> _dispatch = new List<ushort>();

        private ushort _nmiTarget;
        private bool _hasNmi;

        public Lifter(
            NesRom rom,
            AnalysisResult model,
            string gameName,
            CartMapping mapping,
            IBoard board)
        {
            _rom = rom;
            _model = model;
            _nsName = SanitizeIdentifier(gameName);
            _mapping = mapping;
            _board = board;

            BuildLabels();
            BuildDispatch();

            _nmiTarget = _rom.ReadVector(0xFFFA);
            _hasNmi = IsEmittableLabel(_nmiTarget) && _labels.ContainsKey(_nmiTarget);
        }

        // ================================================================
        // Label / dispatch construction
        // ================================================================

        private void BuildLabels()
        {
            foreach (ushort a in _model.Labels)
            {
                if (IsEmittableLabel(a))
                    _labels[a] = true;
            }

            if (IsEmittableLabel(_model.Entry))
                _labels[_model.Entry] = true;

            _emitted.Clear();
            _emitted.AddRange(_labels.Keys);
            _emitted.Sort();
        }

        private void BuildDispatch()
        {
            List<ushort> dispatch = new List<ushort>();

            // Functions / entry points
            foreach (ushort a in _model.Functions)
            {
                if (_labels.ContainsKey(a) && !dispatch.Contains(a))
                    dispatch.Add(a);
            }

            // Known dynamic targets
            foreach (ushort a in _model.DynamicTargets)
            {
                if (_labels.ContainsKey(a) && !dispatch.Contains(a))
                    dispatch.Add(a);
            }

            // Return addresses after JSR, and static JMP targets
            foreach (Instruction inst in _model.Instructions.Values)
            {
                if (inst.Control == OpControl.Jsr &&
                    inst.HasFallthrough &&
                    _labels.ContainsKey(inst.Fallthrough) &&
                    !dispatch.Contains(inst.Fallthrough))
                {
                    dispatch.Add(inst.Fallthrough);
                }

                if ((inst.Control == OpControl.Jmp || inst.Control == OpControl.JmpInd) &&
                    inst.HasTarget &&
                    _labels.ContainsKey(inst.Target) &&
                    !dispatch.Contains(inst.Target))
                {
                    dispatch.Add(inst.Target);
                }
            }

            if (dispatch.Count == 0 && _model.Entry != 0 && _labels.ContainsKey(_model.Entry))
                dispatch.Add(_model.Entry);

            dispatch.Sort();
            _dispatch.Clear();
            _dispatch.AddRange(dispatch);
        }

        private bool IsEmittableLabel(ushort addr)
        {
            if (addr < 0x8000) return false;
            if (addr >= 0xFFFA) return false;
            return _model.Instructions.ContainsKey(addr);
        }

        // ================================================================
        // Code generation
        // ================================================================

        public string Generate()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// NES static recompiler generated code.");
            sb.AppendLine("// Runtime: .NET WinForms. PPU renders to window.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Drawing;");
            sb.AppendLine("using System.Drawing.Imaging;");
            sb.AppendLine("using System.Windows.Forms;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine();
            sb.AppendLine("namespace Lifted." + _nsName);
            sb.AppendLine("{");

            AppendProgram(sb);
            AppendRuntime(sb);
            AppendMemory(sb);
            AppendPpu(sb);
            AppendApu(sb);
            AppendMapper(sb);
            AppendForm(sb);

            sb.AppendLine("}");

            return sb.ToString();
        }

        // ================================================================
        // Program
        // ================================================================

        private void AppendProgram(StringBuilder sb)
        {
            sb.AppendLine("static class Program");
            sb.AppendLine("{");
            sb.AppendLine("    [STAThread]");
            sb.AppendLine("    static void Main()");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            Application.EnableVisualStyles();");
            sb.AppendLine("            Runtime.Init();");
            sb.AppendLine();
            sb.AppendLine("            PpuForm form = new PpuForm();");
            sb.AppendLine();
            sb.AppendLine("            Thread cpuThread = new Thread(new ThreadStart(Runtime.CpuThread));");
            sb.AppendLine("            cpuThread.IsBackground = true;");
            sb.AppendLine("            cpuThread.Priority = ThreadPriority.BelowNormal;");
            sb.AppendLine("            cpuThread.Start();");
            sb.AppendLine();
            sb.AppendLine("            Application.Run(form);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            MessageBox.Show(ex.ToString(), \"NES Lifted fatal\", MessageBoxButtons.OK, MessageBoxIcon.Error);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ================================================================
        // Runtime
        // ================================================================

        private void AppendRuntime(StringBuilder sb)
        {
            CartInfo cart = _rom.Cart;

            sb.AppendLine("static class Runtime");
            sb.AppendLine("{");

            // Metadata
            sb.AppendLine("    public const string GameName = \"" + _nsName + "\";");
            sb.AppendLine("    public const int Mapper = " + cart.Mapper + ";");
            int mir = cart.Mirroring == 1 ? 1 : (cart.Mirroring == 2 ? 2 : 0);
            sb.AppendLine("    public const int Mirroring = " + mir + ";");
            sb.AppendLine();

            // ROM data
            AppendByteArrayField(sb, "PrgRom", _rom.PrgRom);
            AppendByteArrayField(sb, "ChrRom", _rom.ChrRom);
            sb.AppendLine();

            // RAM
            sb.AppendLine("    public static byte[] Ram = new byte[0x800];");
            sb.AppendLine("    public static byte[] SaveRam = new byte[0x2000];");
            sb.AppendLine();

            // CPU registers
            sb.AppendLine("    public static byte A;");
            sb.AppendLine("    public static byte X;");
            sb.AppendLine("    public static byte Y;");
            sb.AppendLine("    public static byte SP;");
            sb.AppendLine("    public static byte P;");
            sb.AppendLine();

            // State
            sb.AppendLine("    public static string LastError;");
            sb.AppendLine("    public static long InsCount;");
            sb.AppendLine("    public static ushort LastPC;");
            sb.AppendLine("    public static ushort DispatchTarget;");
            sb.AppendLine("    public static volatile string CpuState;");
            sb.AppendLine("    public static volatile int TrapCount;");
            sb.AppendLine("    public static string LastTrap;");
            sb.AppendLine();

            // Dynamic dispatch
            sb.AppendLine("    public static object DynLock = new object();");
            sb.AppendLine("    public static System.Collections.Generic.Dictionary<ushort, bool> SeenDynamic = new System.Collections.Generic.Dictionary<ushort, bool>();");
            sb.AppendLine();

            // NMI
            sb.AppendLine("    public static volatile bool NmiPending;");
            sb.AppendLine("    public static volatile bool InNmi;");
            sb.AppendLine("    public static ushort NmiVector = 0x" + _nmiTarget.ToString("X4") + ";");
            sb.AppendLine();

            // Throttle
            sb.AppendLine("    public static long ClockStart = System.Diagnostics.Stopwatch.GetTimestamp();");
            sb.AppendLine("    public static volatile bool ThrottleEnabled = true;");
            sb.AppendLine("    public static long CpuCycles = 0;");
            sb.AppendLine("    public static long NextVblankCycle = 29780;");
            sb.AppendLine("    public static long NmiEnterCycles;");
            sb.AppendLine();

            // Frame sync
            sb.AppendLine("    public static object FrameLock = new object();");
            sb.AppendLine("    public static volatile bool OsdFull;");
            sb.AppendLine();

            // Input
            sb.AppendLine("    public static byte Joy1Buttons;");
            sb.AppendLine("    public static byte Joy2Buttons;");
            sb.AppendLine("    public static byte Joy1Latch;");
            sb.AppendLine("    public static byte Joy2Latch;");
            sb.AppendLine("    public static int Joy1Idx;");
            sb.AppendLine("    public static int Joy2Idx;");
            sb.AppendLine();

            // Init
            sb.AppendLine("    public static void Init()");
            sb.AppendLine("    {");
            sb.AppendLine("        A = 0; X = 0; Y = 0; SP = 0xFD; P = 0x24;");
            sb.AppendLine("        DispatchTarget = 0; CpuState = \"Init\";");
            sb.AppendLine("        Memory.Reset(); Ppu.Reset(); Apu.Reset(); MapperStub.Reset();");
            sb.AppendLine("    }");
            sb.AppendLine();

            // CpuThread
            sb.AppendLine("    public static void CpuThread()");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            CpuState = \"Starting\";");
            sb.AppendLine("            Reset();");
            sb.AppendLine("            CpuState = \"EnteringRun\";");
            sb.AppendLine("            Run();");
            sb.AppendLine("            CpuState = LastError != null ? \"Trap\" : \"Exited\";");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            CpuState = \"Exception\";");
            sb.AppendLine("            OnCpuException(ex);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Reset
            sb.AppendLine("    public static void Reset()");
            sb.AppendLine("    {");
            sb.AppendLine("        A = 0; X = 0; Y = 0; SP = 0xFD; P = 0x24;");
            sb.AppendLine("        LastError = null; LastTrap = null; InsCount = 0; LastPC = 0;");
            sb.AppendLine("        TrapCount = 0; DispatchTarget = 0; CpuState = \"Reset\";");
            sb.AppendLine("        CpuCycles = 0; NextVblankCycle = 29780;");
            sb.AppendLine("        ClockStart = System.Diagnostics.Stopwatch.GetTimestamp();");
            sb.AppendLine("        if (SeenDynamic != null) SeenDynamic.Clear();");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Run
            AppendRun(sb);

            // Helpers
            AppendRuntimeHelpers(sb);

            // Interpreter
            AppendInterpreter(sb);

            sb.AppendLine("}");
            sb.AppendLine();
        }

        private void AppendRun(StringBuilder sb)
        {
            bool hasEntry = _model.Entry != 0 && _labels.ContainsKey(_model.Entry);

            sb.AppendLine("    public static void Run()");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            Line(sb, "Runtime.CpuState = \"Running\";");
            Line(sb, "Console.WriteLine(\"CPU started. Entry: 0x" + _model.Entry.ToString("X4") + "\");");
            Line(sb, "Console.WriteLine(\"Press Ctrl+C to exit.\");");

            if (hasEntry)
                Line(sb, "goto L" + _model.Entry.ToString("X4") + ";");
            else
                Line(sb, "Runtime.Trap(\"No valid entry/reset vector.\"); return;");

            // Dispatch table
            if (_emitted.Count > 0)
            {
                sb.AppendLine("    Dispatch:");
                sb.AppendLine("        {");
                Line(sb, "switch (Runtime.DispatchTarget)");
                Line(sb, "{");
                foreach (ushort daddr in _emitted)
                    Line(sb, "case 0x" + daddr.ToString("X4") + ": goto L" + daddr.ToString("X4") + ";");
                Line(sb, "default: Runtime.ReportDynamicTarget(Runtime.DispatchTarget); if (!Runtime.Interpret()) { Runtime.Trap(\"Dynamic dispatch -> $\" + Runtime.DispatchTarget.ToString(\"X4\")); return; } goto Dispatch;");
                Line(sb, "}");
                sb.AppendLine("        }");
            }

            // Emitted instructions
            foreach (ushort addr in _emitted)
            {
                sb.AppendLine("    L" + addr.ToString("X4") + ":");
                sb.AppendLine("        {");

                Instruction inst = null;
                _model.Instructions.TryGetValue(addr, out inst);

                Line(sb, "Runtime.LastPC = 0x" + addr.ToString("X4") + ";");

                if (inst != null && inst.Info != null)
                    Line(sb, "Runtime.InsCount++; Runtime.CpuCycles += " + inst.Info.Cycles + ";");
                else
                    Line(sb, "Runtime.InsCount++; Runtime.CpuCycles++;");

                if (_hasNmi)
                    Line(sb, "if (Runtime.CheckNmi(0x" + addr.ToString("X4") + ")) goto L" + _nmiTarget.ToString("X4") + ";");

                if (inst != null)
                {
                    Line(sb, "// " + inst.Text);
                    EmitInstruction(sb, inst);
                }
                else
                {
                    Line(sb, "Runtime.Trap(\"Label without instruction.\"); return;");
                }

                sb.AppendLine("        }");
            }

            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception ex) { OnCpuException(ex); }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void AppendRuntimeHelpers(StringBuilder sb)
        {
            sb.AppendLine("    public static void SetCarry(bool v) { P = (byte)(v ? (P | 0x01) : (P & 0xFE)); }");
            sb.AppendLine("    public static void SetZero(bool v) { P = (byte)(v ? (P | 0x02) : (P & 0xFD)); }");
            sb.AppendLine("    public static void SetInterrupt(bool v) { P = (byte)(v ? (P | 0x04) : (P & 0xFB)); }");
            sb.AppendLine("    public static void SetDecimal(bool v) { P = (byte)(v ? (P | 0x08) : (P & 0xF7)); }");
            sb.AppendLine("    public static void SetOverflow(bool v) { P = (byte)(v ? (P | 0x40) : (P & 0xBF)); }");
            sb.AppendLine("    public static void SetNegative(bool v) { P = (byte)(v ? (P | 0x80) : (P & 0x7F)); }");
            sb.AppendLine("    public static void SetNZ(byte v) { P = (byte)((P & 0x7D) | (v == 0 ? 0x02 : 0) | (v & 0x80)); }");
            sb.AppendLine();
            sb.AppendLine("    public static byte Asl(byte v) { SetCarry((v & 0x80) != 0); v = (byte)(v << 1); SetNZ(v); return v; }");
            sb.AppendLine("    public static byte Lsr(byte v) { SetCarry((v & 0x01) != 0); v = (byte)(v >> 1); SetNZ(v); return v; }");
            sb.AppendLine("    public static byte Rol(byte v) { int c = (P & 0x01); SetCarry((v & 0x80) != 0); v = (byte)((v << 1) | c); SetNZ(v); return v; }");
            sb.AppendLine("    public static byte Ror(byte v) { int c = (P & 0x01); SetCarry((v & 0x01) != 0); v = (byte)((v >> 1) | (c << 7)); SetNZ(v); return v; }");
            sb.AppendLine();
            sb.AppendLine("    public static void Adc(byte v)");
            sb.AppendLine("    {");
            sb.AppendLine("        int aa = A; int vv = v; int c = (P & 0x01); int sum = aa + vv + c;");
            sb.AppendLine("        SetOverflow(((~(aa ^ vv) & (aa ^ sum)) & 0x80) != 0);");
            sb.AppendLine("        SetCarry(sum > 0xFF);");
            sb.AppendLine("        A = (byte)sum; SetNZ(A);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void Sbc(byte v)");
            sb.AppendLine("    {");
            sb.AppendLine("        int aa = A; int vv = v; int c = (P & 0x01); int diff = aa - vv - (1 - c);");
            sb.AppendLine("        SetOverflow((((aa ^ vv) & (aa ^ diff)) & 0x80) != 0);");
            sb.AppendLine("        SetCarry(diff >= 0);");
            sb.AppendLine("        A = (byte)diff; SetNZ(A);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void Compare(byte reg, byte v) { int diff = reg - v; SetCarry(reg >= v); SetNZ((byte)diff); }");
            sb.AppendLine("    public static void Bit(byte v) { SetZero((A & v) == 0); SetOverflow((v & 0x40) != 0); SetNegative((v & 0x80) != 0); }");
            sb.AppendLine();
            sb.AppendLine("    public static ushort ReadPtrZp(byte ptr)");
            sb.AppendLine("    {");
            sb.AppendLine("        byte lo = Memory.Read(ptr);");
            sb.AppendLine("        byte hi = Memory.Read((byte)(ptr + 1));");
            sb.AppendLine("        return (ushort)(lo | (hi << 8));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static ushort AddrXInd(byte op) { return ReadPtrZp((byte)(op + X)); }");
            sb.AppendLine("    public static ushort AddrIndY(byte op) { return (ushort)(ReadPtrZp(op) + Y); }");
            sb.AppendLine();
            sb.AppendLine("    public static void Push(byte v) { Memory.Write((ushort)(0x100 + SP), v); SP = (byte)(SP - 1); }");
            sb.AppendLine("    public static byte Pull() { SP = (byte)(SP + 1); return Memory.Read((ushort)(0x100 + SP)); }");
            sb.AppendLine("    public static void Push16(ushort v) { Push((byte)(v >> 8)); Push((byte)(v & 0xFF)); }");
            sb.AppendLine("    public static ushort Pull16() { byte lo = Pull(); byte hi = Pull(); return (ushort)(lo | (hi << 8)); }");
            sb.AppendLine("    public static void JsrPush(ushort returnAddress) { Push16((ushort)(returnAddress - 1)); }");
            sb.AppendLine("    public static ushort RtsPull() { return (ushort)(Pull16() + 1); }");
            sb.AppendLine();

            // === Input ===
            sb.AppendLine("    public static void JoyStrobe(byte v) { if ((v & 1) != 0) { Joy1Latch = Joy1Buttons; Joy2Latch = Joy2Buttons; Joy1Idx = 0; Joy2Idx = 0; } }");
            sb.AppendLine("    public static byte JoyRead1() { int i = Joy1Idx; Joy1Idx = i + 1; if (i < 8) return (byte)((Joy1Latch >> i) & 1); return 0; }");
            sb.AppendLine("    public static byte JoyRead2() { int i = Joy2Idx; Joy2Idx = i + 1; if (i < 8) return (byte)((Joy2Latch >> i) & 1); return 0; }");
            sb.AppendLine();

            // === Throttle ===
            sb.AppendLine("    public static void Throttle()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (!ThrottleEnabled) return;");
            sb.AppendLine("        long freq = System.Diagnostics.Stopwatch.Frequency;");
            sb.AppendLine("        long now = System.Diagnostics.Stopwatch.GetTimestamp();");
            sb.AppendLine("        long elapsedCycles = (now - ClockStart) * 1789773L / freq;");
            sb.AppendLine("        long ahead = CpuCycles - elapsedCycles;");
            sb.AppendLine("        if (ahead <= 1789L) return;");
            sb.AppendLine("        if (ahead > 100000L) { ClockStart = now - (CpuCycles - 1789L) * freq / 1789773L; return; }");
            sb.AppendLine("        long targetTimestamp = ClockStart + (CpuCycles - 1789L) * freq / 1789773L;");
            sb.AppendLine("        long maxTs = now + 50000L * freq / 1000000L;");
            sb.AppendLine("        if (targetTimestamp > maxTs) targetTimestamp = maxTs;");
            sb.AppendLine("        long t;");
            sb.AppendLine("        while ((t = System.Diagnostics.Stopwatch.GetTimestamp()) < targetTimestamp)");
            sb.AppendLine("        {");
            sb.AppendLine("            long leftUs = (targetTimestamp - t) * 1000000L / freq;");
            sb.AppendLine("            if (leftUs > 1500L) System.Threading.Thread.Sleep(1);");
            sb.AppendLine("            else System.Threading.Thread.SpinWait(50);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // === CheckNmi with cycle-based VBlank ===
            sb.AppendLine("    public static bool CheckNmi(ushort pc)");
            sb.AppendLine("    {");
            sb.AppendLine("        if ((CpuCycles & 2047) == 0) Throttle();");
            sb.AppendLine();
            sb.AppendLine("        if (CpuCycles >= NextVblankCycle)");
            sb.AppendLine("        {");
            sb.AppendLine("            NextVblankCycle += 29780;");
            sb.AppendLine("            NmiPending = true;");
            sb.AppendLine("            Ppu.Status = (byte)(Ppu.Status | 0x80);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (InNmi && (CpuCycles - NmiEnterCycles) > 1500000L) InNmi = false;");
            sb.AppendLine();
            sb.AppendLine("        if (!NmiPending || InNmi || (Ppu.Ctrl & 0x80) == 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            if ((Ppu.Ctrl & 0x80) == 0) NmiPending = false;");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        NmiPending = false;");
            sb.AppendLine("        InNmi = true;");
            sb.AppendLine("        NmiEnterCycles = CpuCycles;");
            sb.AppendLine();
            sb.AppendLine("        Push16(pc);");
            sb.AppendLine("        Push((byte)((P & 0xEF) | 0x20));");
            sb.AppendLine("        P = (byte)(P | 0x04);");
            sb.AppendLine();
            sb.AppendLine("        return true;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Trap / error handling
            sb.AppendLine("    public static void Trap(string message) { SetTrap(message); }");
            sb.AppendLine("    public static void UnknownOpcode(byte op, ushort addr) { SetTrap(string.Format(\"Unknown opcode ${0:X2} at ${1:X4}\", op, addr)); }");
            sb.AppendLine("    public static void OnCpuException(Exception ex) { SetTrap(\"CPU exception: \" + ex); }");
            sb.AppendLine();
            sb.AppendLine("    public static void SetTrap(string message)");
            sb.AppendLine("    {");
            sb.AppendLine("        LastError = message;");
            sb.AppendLine("        CpuState = \"Trap\";");
            sb.AppendLine("        if (LastTrap != message) { LastTrap = message; TrapCount++; Console.WriteLine(\"TRAP: \" + message); }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Dynamic target reporting
            sb.AppendLine("    public static void ReportDynamicTarget(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (addr < 0x8000 || addr >= 0xFFFA) return;");
            sb.AppendLine("        lock (DynLock)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!SeenDynamic.ContainsKey(addr))");
            sb.AppendLine("            {");
            sb.AppendLine("                SeenDynamic.Add(addr, true);");
            sb.AppendLine("                try { System.IO.File.AppendAllText(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, \"dynamic_targets.log\"), addr.ToString(\"X4\") + System.Environment.NewLine); } catch { }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ================================================================
        // Interpreter (fallback for dynamic targets)
        // ================================================================

        private void AppendInterpreter(StringBuilder sb)
        {
            // OpLen table
            sb.Append("    public static readonly byte[] OpLen = new byte[256]{");
            for (int i = 0; i < 256; i++)
            {
                if (i > 0) sb.Append(",");
                OpInfo oi = Cpu6502.Table[i];
                int len = (oi == null) ? 1 : oi.Len;
                sb.Append(len.ToString(CultureInfo.InvariantCulture));
            }
            sb.AppendLine("};");

            // OpCycles table
            sb.Append("    public static readonly byte[] OpCycles = new byte[256]{");
            for (int i = 0; i < 256; i++)
            {
                if (i > 0) sb.Append(",");
                OpInfo oi = Cpu6502.Table[i];
                int cyc = (oi == null) ? 1 : oi.Cycles;
                sb.Append(cyc.ToString(CultureInfo.InvariantCulture));
            }
            sb.AppendLine("};");

            // OpMnem table
            sb.Append("    public static readonly byte[] OpMnem = new byte[256]{");
            for (int i = 0; i < 256; i++)
            {
                if (i > 0) sb.Append(",");
                sb.Append(MnemIdFor(Cpu6502.Table[i]).ToString(CultureInfo.InvariantCulture));
            }
            sb.AppendLine("};");

            // OpMode table
            sb.Append("    public static readonly byte[] OpMode = new byte[256]{");
            for (int i = 0; i < 256; i++)
            {
                if (i > 0) sb.Append(",");
                OpInfo oi = Cpu6502.Table[i];
                int m = (oi == null) ? 0 : (int)oi.Mode;
                sb.Append(m.ToString(CultureInfo.InvariantCulture));
            }
            sb.AppendLine("};");

            // IsStaticLabel
            sb.AppendLine("    public static bool IsStaticLabel(ushort a)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (a) {");
            foreach (ushort a in _emitted)
                sb.AppendLine("            case 0x" + a.ToString("X4") + ": return true;");
            sb.AppendLine("            default: return false;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ReadOp
            sb.AppendLine("    static byte ReadOp(byte mode, ushort pc, byte imm)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (mode) {");
            sb.AppendLine("            case 1: return A;");
            sb.AppendLine("            case 2: return imm;");
            sb.AppendLine("            case 3: return Memory.Read(imm);");
            sb.AppendLine("            case 4: return Memory.Read((byte)(imm + X));");
            sb.AppendLine("            case 5: return Memory.Read((byte)(imm + Y));");
            sb.AppendLine("            case 6: return Memory.Read(Memory.Read16((ushort)(pc + 1)));");
            sb.AppendLine("            case 7: return Memory.Read(unchecked((ushort)(Memory.Read16((ushort)(pc + 1)) + X)));");
            sb.AppendLine("            case 8: return Memory.Read(unchecked((ushort)(Memory.Read16((ushort)(pc + 1)) + Y)));");
            sb.AppendLine("            case 10: return Memory.Read(AddrXInd(imm));");
            sb.AppendLine("            case 11: return Memory.Read(AddrIndY(imm));");
            sb.AppendLine("            default: return 0;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // AddrOp
            sb.AppendLine("    static ushort AddrOp(byte mode, ushort pc, byte imm)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (mode) {");
            sb.AppendLine("            case 3: return imm;");
            sb.AppendLine("            case 4: return (byte)(imm + X);");
            sb.AppendLine("            case 5: return (byte)(imm + Y);");
            sb.AppendLine("            case 6: return Memory.Read16((ushort)(pc + 1));");
            sb.AppendLine("            case 7: return unchecked((ushort)(Memory.Read16((ushort)(pc + 1)) + X));");
            sb.AppendLine("            case 8: return unchecked((ushort)(Memory.Read16((ushort)(pc + 1)) + Y));");
            sb.AppendLine("            case 10: return AddrXInd(imm);");
            sb.AppendLine("            case 11: return AddrIndY(imm);");
            sb.AppendLine("            default: return 0;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Interpret
            sb.AppendLine("    public static bool Interpret()");
            sb.AppendLine("    {");
            sb.AppendLine("        ushort pc = DispatchTarget;");
            sb.AppendLine("        for (int g = 0; g < 100000; g++)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (CheckNmi(pc)) { DispatchTarget = NmiVector; return true; }");
            sb.AppendLine("            if (IsStaticLabel(pc)) { DispatchTarget = pc; return true; }");
            sb.AppendLine("            byte op = Memory.Read(pc);");
            sb.AppendLine("            LastPC = pc; InsCount++; CpuCycles += OpCycles[op];");
            sb.AppendLine("            byte mnem = OpMnem[op];");
            sb.AppendLine("            byte mode = OpMode[op];");
            sb.AppendLine("            byte len = OpLen[op];");
            sb.AppendLine("            byte imm = (len >= 2) ? Memory.Read((ushort)(pc + 1)) : (byte)0;");
            sb.AppendLine();

            // Control flow
            sb.AppendLine("            switch (mnem) {");
            sb.AppendLine("                case 44: { ushort tgt; if (mode == 9) { ushort ptr = Memory.Read16((ushort)(pc + 1)); ushort loAddr = ptr; ushort hiAddr = (ushort)((ptr & 0xFF00) | ((ptr + 1) & 0x00FF)); tgt = (ushort)(Memory.Read(loAddr) | (Memory.Read(hiAddr) << 8)); } else { tgt = Memory.Read16((ushort)(pc + 1)); } if (IsStaticLabel(tgt)) { DispatchTarget = tgt; return true; } pc = tgt; continue; }");
            sb.AppendLine("                case 45: { JsrPush((ushort)(pc + 3)); ushort tgt = Memory.Read16((ushort)(pc + 1)); if (IsStaticLabel(tgt)) { DispatchTarget = tgt; return true; } pc = tgt; continue; }");
            sb.AppendLine("                case 46: { ushort tgt = RtsPull(); if (IsStaticLabel(tgt)) { DispatchTarget = tgt; return true; } pc = tgt; continue; }");
            sb.AppendLine("                case 47: { P = (byte)((Pull() & 0xEF) | 0x20); ushort tgt = Pull16(); InNmi = false; if (IsStaticLabel(tgt)) { DispatchTarget = tgt; return true; } pc = tgt; continue; }");
            sb.AppendLine("                case 48: { Push16((ushort)(pc + 2)); Push((byte)(P | 0x30)); P = (byte)(P | 0x04); ushort tgt = Memory.Read16(0xFFFE); if (IsStaticLabel(tgt)) { DispatchTarget = tgt; return true; } pc = tgt; continue; }");
            sb.AppendLine("                case 49: { bool c; switch (op) { case 0x10: c = (P & 0x80) == 0; break; case 0x30: c = (P & 0x80) != 0; break; case 0x50: c = (P & 0x40) == 0; break; case 0x70: c = (P & 0x40) != 0; break; case 0x90: c = (P & 0x01) == 0; break; case 0xB0: c = (P & 0x01) != 0; break; case 0xD0: c = (P & 0x02) == 0; break; case 0xF0: c = (P & 0x02) != 0; break; default: c = false; break; } ushort nxt = c ? (ushort)(pc + 2 + (sbyte)imm) : (ushort)(pc + 2); if (IsStaticLabel(nxt)) { DispatchTarget = nxt; return true; } pc = nxt; continue; }");
            sb.AppendLine("            }");
            sb.AppendLine();

            // Normal instructions
            sb.AppendLine("            byte val = ReadOp(mode, pc, imm);");
            sb.AppendLine("            switch (mnem) {");
            sb.AppendLine("                case 1: A = val; SetNZ(A); break;");
            sb.AppendLine("                case 2: X = val; SetNZ(X); break;");
            sb.AppendLine("                case 3: Y = val; SetNZ(Y); break;");
            sb.AppendLine("                case 4: Memory.Write(AddrOp(mode, pc, imm), A); break;");
            sb.AppendLine("                case 5: Memory.Write(AddrOp(mode, pc, imm), X); break;");
            sb.AppendLine("                case 6: Memory.Write(AddrOp(mode, pc, imm), Y); break;");
            sb.AppendLine("                case 7: X = A; SetNZ(X); break;");
            sb.AppendLine("                case 8: Y = A; SetNZ(Y); break;");
            sb.AppendLine("                case 9: A = X; SetNZ(A); break;");
            sb.AppendLine("                case 10: A = Y; SetNZ(A); break;");
            sb.AppendLine("                case 11: SP = X; break;");
            sb.AppendLine("                case 12: X = SP; SetNZ(X); break;");
            sb.AppendLine("                case 13: X = (byte)(X + 1); SetNZ(X); break;");
            sb.AppendLine("                case 14: Y = (byte)(Y + 1); SetNZ(Y); break;");
            sb.AppendLine("                case 15: X = (byte)(X - 1); SetNZ(X); break;");
            sb.AppendLine("                case 16: Y = (byte)(Y - 1); SetNZ(Y); break;");
            sb.AppendLine("                case 17: Adc(val); break;");
            sb.AppendLine("                case 18: Sbc(val); break;");
            sb.AppendLine("                case 19: Compare(A, val); break;");
            sb.AppendLine("                case 20: Compare(X, val); break;");
            sb.AppendLine("                case 21: Compare(Y, val); break;");
            sb.AppendLine("                case 22: A = (byte)(A & val); SetNZ(A); break;");
            sb.AppendLine("                case 23: A = (byte)(A | val); SetNZ(A); break;");
            sb.AppendLine("                case 24: A = (byte)(A ^ val); SetNZ(A); break;");
            sb.AppendLine("                case 25: Bit(val); break;");
            sb.AppendLine("                case 26: if (mode == 1) A = Asl(A); else { ushort a = AddrOp(mode, pc, imm); Memory.Write(a, Asl(Memory.Read(a))); } break;");
            sb.AppendLine("                case 27: if (mode == 1) A = Lsr(A); else { ushort a = AddrOp(mode, pc, imm); Memory.Write(a, Lsr(Memory.Read(a))); } break;");
            sb.AppendLine("                case 28: if (mode == 1) A = Rol(A); else { ushort a = AddrOp(mode, pc, imm); Memory.Write(a, Rol(Memory.Read(a))); } break;");
            sb.AppendLine("                case 29: if (mode == 1) A = Ror(A); else { ushort a = AddrOp(mode, pc, imm); Memory.Write(a, Ror(Memory.Read(a))); } break;");
            sb.AppendLine("                case 30: { ushort a = AddrOp(mode, pc, imm); byte t = (byte)(Memory.Read(a) + 1); SetNZ(t); Memory.Write(a, t); } break;");
            sb.AppendLine("                case 31: { ushort a = AddrOp(mode, pc, imm); byte t = (byte)(Memory.Read(a) - 1); SetNZ(t); Memory.Write(a, t); } break;");
            sb.AppendLine("                case 32: P = (byte)(P & 0xFE); break;");
            sb.AppendLine("                case 33: P = (byte)(P | 0x01); break;");
            sb.AppendLine("                case 34: P = (byte)(P & 0xFB); break;");
            sb.AppendLine("                case 35: P = (byte)(P | 0x04); break;");
            sb.AppendLine("                case 36: P = (byte)(P & 0xBF); break;");
            sb.AppendLine("                case 37: P = (byte)(P & 0xF7); break;");
            sb.AppendLine("                case 38: P = (byte)(P | 0x08); break;");
            sb.AppendLine("                case 39: Push(A); break;");
            sb.AppendLine("                case 40: A = Pull(); SetNZ(A); break;");
            sb.AppendLine("                case 41: Push((byte)(P | 0x30)); break;");
            sb.AppendLine("                case 42: P = (byte)((Pull() & 0xEF) | 0x20); break;");
            sb.AppendLine("                case 43: break;");
            sb.AppendLine("                case 50: A = X = val; SetNZ(A); break;");
            sb.AppendLine("                case 51: Memory.Write(AddrOp(mode, pc, imm), (byte)(A & X)); break;");
            sb.AppendLine("                case 52: { ushort a = AddrOp(mode, pc, imm); byte t = (byte)(Memory.Read(a) - 1); Memory.Write(a, t); Compare(A, t); } break;");
            sb.AppendLine("                case 53: { ushort a = AddrOp(mode, pc, imm); byte t = (byte)(Memory.Read(a) + 1); Memory.Write(a, t); Sbc(t); } break;");
            sb.AppendLine("                case 54: { ushort a = AddrOp(mode, pc, imm); byte t = Asl(Memory.Read(a)); Memory.Write(a, t); A = (byte)(A | t); SetNZ(A); } break;");
            sb.AppendLine("                case 55: { ushort a = AddrOp(mode, pc, imm); byte t = Rol(Memory.Read(a)); Memory.Write(a, t); A = (byte)(A & t); SetNZ(A); } break;");
            sb.AppendLine("                case 56: { ushort a = AddrOp(mode, pc, imm); byte t = Lsr(Memory.Read(a)); Memory.Write(a, t); A = (byte)(A ^ t); SetNZ(A); } break;");
            sb.AppendLine("                case 57: { ushort a = AddrOp(mode, pc, imm); byte t = Ror(Memory.Read(a)); Memory.Write(a, t); Adc(t); } break;");
            sb.AppendLine("                case 58: A = (byte)(A & val); SetCarry((A & 0x80) != 0); SetNZ(A); break;");
            sb.AppendLine("                case 59: A = Lsr((byte)(A & val)); break;");
            sb.AppendLine("                case 60: A = Ror((byte)(A & val)); break;");
            sb.AppendLine("                case 61: A = (byte)((A | 0xEE) & X & val); SetNZ(A); break;");
            sb.AppendLine("                case 62: A = (byte)((A | 0xEE) & val); X = A; SetNZ(A); break;");
            sb.AppendLine("                case 63: { int t = (A & X) - val; X = (byte)t; SetCarry(t >= 0); SetNZ(X); } break;");
            sb.AppendLine("                case 64: Memory.Write(AddrOp(mode, pc, imm), Y); break;");
            sb.AppendLine("                case 65: SP = (byte)(SP & val); A = SP; X = SP; SetNZ(SP); break;");
            sb.AppendLine("                case 66: Memory.Write(AddrOp(mode, pc, imm), (byte)(A & X)); break;");
            sb.AppendLine("                case 67: DispatchTarget = pc; return false;");
            sb.AppendLine("                default: DispatchTarget = pc; return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            pc = (ushort)(pc + len);");
            sb.AppendLine("        }");
            sb.AppendLine("        DispatchTarget = pc;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // ================================================================
        // Memory
        // ================================================================

        private void AppendMemory(StringBuilder sb)
        {
            sb.AppendLine("static class Memory");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Reset()");
            sb.AppendLine("    {");
            sb.AppendLine("        Array.Clear(Runtime.Ram, 0, Runtime.Ram.Length);");
            sb.AppendLine("        Array.Clear(Runtime.SaveRam, 0, Runtime.SaveRam.Length);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static byte Read(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (addr < 0x2000) return Runtime.Ram[addr & 0x07FF];");
            sb.AppendLine("        if (addr < 0x4000) return Ppu.ReadReg((ushort)(0x2000 + (addr & 7)));");
            sb.AppendLine("        if (addr < 0x4020) return Apu.ReadReg(addr);");
            sb.AppendLine("        if (addr < 0x6000) return MapperStub.Read(addr);");
            sb.AppendLine("        if (addr < 0x8000) return Runtime.SaveRam[addr - 0x6000];");
            sb.AppendLine("        return ReadPrg(addr);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void Write(ushort addr, byte value)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (addr < 0x2000) { Runtime.Ram[addr & 0x07FF] = value; return; }");
            sb.AppendLine("        if (addr < 0x4000) { Ppu.WriteReg((ushort)(0x2000 + (addr & 7)), value); return; }");
            sb.AppendLine("        if (addr < 0x4020)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (addr == 0x4014) { Ppu.DmaOam(value); return; }");
            sb.AppendLine("            Apu.WriteReg(addr, value); return;");
            sb.AppendLine("        }");
            sb.AppendLine("        if (addr < 0x6000) { MapperStub.Write(addr, value); return; }");
            sb.AppendLine("        if (addr < 0x8000) { Runtime.SaveRam[addr - 0x6000] = value; return; }");
            sb.AppendLine("        MapperStub.Write(addr, value);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static ushort Read16(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        return (ushort)(Read(addr) | (Read((ushort)(addr + 1)) << 8));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static byte ReadPrg(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        int len = Runtime.PrgRom.Length;");
            sb.AppendLine("        if (len == 0) return 0;");
            sb.AppendLine("        if (len <= 0x4000)");
            sb.AppendLine("        {");
            sb.AppendLine("            int a = addr >= 0xC000 ? addr - 0xC000 : addr - 0x8000;");
            sb.AppendLine("            if (a < 0) a = addr - 0x8000;");
            sb.AppendLine("            return Runtime.PrgRom[a % len];");
            sb.AppendLine("        }");
            sb.AppendLine("        if (len <= 0x8000) return Runtime.PrgRom[(addr - 0x8000) % len];");
            sb.AppendLine("        int baseIndex = len - 0x8000;");
            sb.AppendLine("        return Runtime.PrgRom[baseIndex + (addr - 0x8000)];");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ================================================================
        // PPU stub
        // ================================================================

        private void AppendPpu(StringBuilder sb)
        {
            sb.AppendLine("static class Ppu");
            sb.AppendLine("{");
            sb.AppendLine("    public static volatile byte Ctrl, Mask, Status, OamAddr, ScrollX, ScrollY;");
            sb.AppendLine("    public static bool WToggle;");
            sb.AppendLine("    public static volatile ushort VRamAddr;");
            sb.AppendLine("    public static byte DataBuffer;");
            sb.AppendLine("    public static byte[] VRam = new byte[0x4000];");
            sb.AppendLine("    public static byte[] Oam = new byte[256];");
            sb.AppendLine("    public static byte[] Palette = new byte[32];");
            sb.AppendLine("    public static byte[] Screen = new byte[256 * 240 * 4];");
            sb.AppendLine("    public static int FrameCount;");
            sb.AppendLine();
            sb.AppendLine("    public static int[] NesPalette = new int[64]");
            sb.AppendLine("    {");
            sb.AppendLine("        0x7C7C7C, 0x0000FC, 0x0000BC, 0x4428BC, 0x940084, 0xA80020, 0xA81000, 0x881400,");
            sb.AppendLine("        0x503000, 0x007800, 0x006800, 0x005800, 0x004058, 0x000000, 0x000000, 0x000000,");
            sb.AppendLine("        0xBCBCBC, 0x0078F8, 0x0058F8, 0x6844FC, 0xD800CC, 0xE40058, 0xF83800, 0xE45C10,");
            sb.AppendLine("        0xAC7C00, 0x00B800, 0x00A800, 0x00A844, 0x008888, 0x000000, 0x000000, 0x000000,");
            sb.AppendLine("        0xF8F8F8, 0x3CBCFC, 0x6888FC, 0x9878F8, 0xF878F8, 0xF85898, 0xF87858, 0xFCA044,");
            sb.AppendLine("        0xF8B800, 0xB8F818, 0x58D854, 0x58F898, 0x00E8D8, 0x787878, 0x000000, 0x000000,");
            sb.AppendLine("        0xFCFCFC, 0xA4E4FC, 0xB8B8F8, 0xD8B8F8, 0xF8B8F8, 0xF8A4C0, 0xF0D0B0, 0xFCE0A8,");
            sb.AppendLine("        0xF8D878, 0xD8F878, 0xB8F8B8, 0xB8F8D8, 0x00FCFC, 0xF8D8F8, 0x000000, 0x000000");
            sb.AppendLine("    };");
            sb.AppendLine();
            sb.AppendLine("    public static void Reset()");
            sb.AppendLine("    {");
            sb.AppendLine("        Ctrl = Mask = OamAddr = ScrollX = ScrollY = 0;");
            sb.AppendLine("        Status = 0x80;");
            sb.AppendLine("        WToggle = false;");
            sb.AppendLine("        VRamAddr = 0;");
            sb.AppendLine("        DataBuffer = 0;");
            sb.AppendLine("        FrameCount = 0;");
            sb.AppendLine("        Array.Clear(VRam, 0, VRam.Length);");
            sb.AppendLine("        Array.Clear(Oam, 0, Oam.Length);");
            sb.AppendLine("        Array.Clear(Palette, 0, Palette.Length);");
            sb.AppendLine("        Array.Clear(Screen, 0, Screen.Length);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static byte ReadReg(ushort reg)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (reg & 7)");
            sb.AppendLine("        {");
            sb.AppendLine("            case 2:");
            sb.AppendLine("            {");
            sb.AppendLine("                byte s = Status;");
            sb.AppendLine("                Status = (byte)(Status & 0x7F);");
            sb.AppendLine("                WToggle = false;");
            sb.AppendLine("                return s;");
            sb.AppendLine("            }");
            sb.AppendLine("            case 4: return Oam[OamAddr];");
            sb.AppendLine("            case 7:");
            sb.AppendLine("            {");
            sb.AppendLine("                ushort addr = (ushort)(VRamAddr & 0x3FFF);");
            sb.AppendLine("                byte data = ReadVram(addr);");
            sb.AppendLine("                byte ret;");
            sb.AppendLine("                if (addr >= 0x3F00) { ret = data; DataBuffer = ReadVram((ushort)(addr - 0x1000)); }");
            sb.AppendLine("                else { ret = DataBuffer; DataBuffer = data; }");
            sb.AppendLine("                VRamAddr = (ushort)(VRamAddr + ((Ctrl & 0x04) != 0 ? 32 : 1));");
            sb.AppendLine("                return ret;");
            sb.AppendLine("            }");
            sb.AppendLine("            default: return 0;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void WriteReg(ushort reg, byte value)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (reg & 7)");
            sb.AppendLine("        {");
            sb.AppendLine("            case 0: Ctrl = value; break;");
            sb.AppendLine("            case 1: Mask = value; break;");
            sb.AppendLine("            case 3: OamAddr = value; break;");
            sb.AppendLine("            case 4: Oam[OamAddr] = value; OamAddr = (byte)(OamAddr + 1); break;");
            sb.AppendLine("            case 5: if (!WToggle) ScrollX = value; else ScrollY = value; WToggle = !WToggle; break;");
            sb.AppendLine("            case 6: if (!WToggle) VRamAddr = (ushort)((value & 0x3F) << 8); else VRamAddr = (ushort)((VRamAddr & 0xFF00) | value); WToggle = !WToggle; break;");
            sb.AppendLine("            case 7: WriteVram(VRamAddr, value); VRamAddr = (ushort)(VRamAddr + ((Ctrl & 0x04) != 0 ? 32 : 1)); break;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void DmaOam(byte page)");
            sb.AppendLine("    {");
            sb.AppendLine("        int baseAddr = page << 8;");
            sb.AppendLine("        for (int i = 0; i < 256; i++) Oam[i] = Memory.Read((ushort)(baseAddr + i));");
            sb.AppendLine("        OamAddr = 0;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // === VRAM helpers ===
            sb.AppendLine("    static ushort MirrorName(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        int table = (addr >> 10) & 3;");
            sb.AppendLine("        int offset = addr & 0x3FF;");
            sb.AppendLine("        if (Runtime.Mirroring == 1) { if (table == 2) table = 0; else if (table == 3) table = 1; }");
            sb.AppendLine("        else if (Runtime.Mirroring == 0) { if (table == 1) table = 0; else if (table >= 2) table = 1; }");
            sb.AppendLine("        return (ushort)(0x2000 + table * 0x400 + offset);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static ushort NormalizeVram(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        addr = (ushort)(addr & 0x3FFF);");
            sb.AppendLine("        if (addr >= 0x3000 && addr < 0x3F00) addr = (ushort)(addr - 0x1000);");
            sb.AppendLine("        if (addr >= 0x2000 && addr < 0x3000) return MirrorName(addr);");
            sb.AppendLine("        if (addr >= 0x3F00) { int idx = (addr - 0x3F00) & 0x1F; if ((idx & 0x13) == 0x10) idx &= 0x0F; return (ushort)(0x3F00 + idx); }");
            sb.AppendLine("        return addr;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static byte ReadVram(ushort addr) { addr = NormalizeVram(addr); if (addr >= 0x3F00) return Palette[(addr - 0x3F00) & 0x1F]; return VRam[addr]; }");
            sb.AppendLine("    static void WriteVram(ushort addr, byte value) { addr = NormalizeVram(addr); if (addr >= 0x3F00) Palette[(addr - 0x3F00) & 0x1F] = value; else VRam[addr] = value; }");
            sb.AppendLine();

            // === Rendering ===
            sb.AppendLine("    public static void RenderScreen()");
            sb.AppendLine("    {");
            sb.AppendLine("        int backdrop = Palette[0] & 0x3F;");
            sb.AppendLine("        FillScreen(backdrop);");
            sb.AppendLine();
            sb.AppendLine("        bool showBG = (Mask & 0x08) != 0;");
            sb.AppendLine("        bool showSpr = (Mask & 0x10) != 0;");
            sb.AppendLine("        if (!showBG && !showSpr) return;");
            sb.AppendLine();
            sb.AppendLine("        int scrollX = ScrollX;");
            sb.AppendLine("        int scrollY = ScrollY;");
            sb.AppendLine("        int nameBase = MirrorName((ushort)(0x2000 + (Ctrl & 0x03) * 0x400));");
            sb.AppendLine("        int patternBase = (Ctrl & 0x10) != 0 ? 0x1000 : 0x0000;");
            sb.AppendLine("        int sprPatternBase = (Ctrl & 0x08) != 0 ? 0x1000 : 0x0000;");
            sb.AppendLine("        bool bigSpr = (Ctrl & 0x20) != 0;");
            sb.AppendLine();
            sb.AppendLine("        if (showBG)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int y = 0; y < 240; y++)");
            sb.AppendLine("            {");
            sb.AppendLine("                int srcY = (y + scrollY) % 240;");
            sb.AppendLine("                int tileY = srcY >> 3;");
            sb.AppendLine("                int py = srcY & 7;");
            sb.AppendLine("                for (int x = 0; x < 256; x++)");
            sb.AppendLine("                {");
            sb.AppendLine("                    int srcX = (x + scrollX) & 0xFF;");
            sb.AppendLine("                    int tileX = srcX >> 3;");
            sb.AppendLine("                    int px = srcX & 7;");
            sb.AppendLine("                    int tileAddr = nameBase + tileY * 32 + tileX;");
            sb.AppendLine("                    byte tile = VRam[tileAddr];");
            sb.AppendLine("                    int pal = GetAttributePalette(nameBase, tileX, tileY);");
            sb.AppendLine("                    int color = GetPatternPixel(patternBase, tile, px, py);");
            sb.AppendLine("                    if (color == 0) continue;");
            sb.AppendLine("                    int finalColor = GetBackgroundColor(pal, color);");
            sb.AppendLine("                    SetPixel(x, y, finalColor);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        if (showSpr)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 63; i >= 0; i--)");
            sb.AppendLine("            {");
            sb.AppendLine("                int sy = Oam[i * 4] + 1;");
            sb.AppendLine("                int tile = Oam[i * 4 + 1];");
            sb.AppendLine("                int attr = Oam[i * 4 + 2];");
            sb.AppendLine("                int sx = Oam[i * 4 + 3];");
            sb.AppendLine("                if (sy >= 240 || sy <= -16) continue;");
            sb.AppendLine("                int pal = attr & 3;");
            sb.AppendLine("                bool flipH = (attr & 0x40) != 0;");
            sb.AppendLine("                bool flipV = (attr & 0x80) != 0;");
            sb.AppendLine("                int height = bigSpr ? 16 : 8;");
            sb.AppendLine("                int tileIndex = tile;");
            sb.AppendLine("                int patBase = sprPatternBase;");
            sb.AppendLine("                if (bigSpr) { patBase = (tile & 1) != 0 ? 0x1000 : 0x0000; tileIndex = tile & 0xFE; }");
            sb.AppendLine("                for (int py = 0; py < height; py++)");
            sb.AppendLine("                {");
            sb.AppendLine("                    int screenY = sy + py;");
            sb.AppendLine("                    if ((uint)screenY >= 240) continue;");
            sb.AppendLine("                    int srcY = flipV ? (height - 1 - py) : py;");
            sb.AppendLine("                    int t = tileIndex;");
            sb.AppendLine("                    int row = srcY;");
            sb.AppendLine("                    if (bigSpr && srcY >= 8) { t = tileIndex + 1; row = srcY - 8; }");
            sb.AppendLine("                    for (int px = 0; px < 8; px++)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        int screenX = sx + px;");
            sb.AppendLine("                        if ((uint)screenX >= 256) continue;");
            sb.AppendLine("                        int srcX = flipH ? (7 - px) : px;");
            sb.AppendLine("                        int color = GetPatternPixel(patBase, t, srcX, row);");
            sb.AppendLine("                        if (color == 0) continue;");
            sb.AppendLine("                        if (i == 0 && screenY > 0 && (Mask & 0x08) != 0) Status = (byte)(Status | 0x40);");
            sb.AppendLine("                        int idx = 0x11 + pal * 4 + (color - 1);");
            sb.AppendLine("                        SetPixel(screenX, screenY, Palette[idx & 0x1F] & 0x3F);");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // === Pixel helpers ===
            sb.AppendLine("    static void FillScreen(int colorIndex)");
            sb.AppendLine("    {");
            sb.AppendLine("        int rgb = NesPalette[colorIndex & 0x3F];");
            sb.AppendLine("        byte b = (byte)(rgb & 0xFF);");
            sb.AppendLine("        byte g = (byte)((rgb >> 8) & 0xFF);");
            sb.AppendLine("        byte r = (byte)((rgb >> 16) & 0xFF);");
            sb.AppendLine("        for (int i = 0; i < Screen.Length; i += 4) { Screen[i] = b; Screen[i + 1] = g; Screen[i + 2] = r; Screen[i + 3] = 0xFF; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static void SetPixel(int x, int y, int colorIndex)");
            sb.AppendLine("    {");
            sb.AppendLine("        if ((uint)x >= 256 || (uint)y >= 240) return;");
            sb.AppendLine("        int rgb = NesPalette[colorIndex & 0x3F];");
            sb.AppendLine("        int off = (y * 256 + x) * 4;");
            sb.AppendLine("        Screen[off] = (byte)(rgb & 0xFF);");
            sb.AppendLine("        Screen[off + 1] = (byte)((rgb >> 8) & 0xFF);");
            sb.AppendLine("        Screen[off + 2] = (byte)((rgb >> 16) & 0xFF);");
            sb.AppendLine("        Screen[off + 3] = 0xFF;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static int GetAttributePalette(int nameBase, int tileX, int tileY)");
            sb.AppendLine("    {");
            sb.AppendLine("        int attrBase = nameBase + 0x3C0;");
            sb.AppendLine("        int ax = tileX >> 2;");
            sb.AppendLine("        int ay = tileY >> 2;");
            sb.AppendLine("        int attr = VRam[attrBase + ay * 8 + ax];");
            sb.AppendLine("        int shift = ((tileY & 2) << 1) | (tileX & 2);");
            sb.AppendLine("        return (attr >> shift) & 3;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static int GetBackgroundColor(int pal, int color)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (color == 0) return Palette[0] & 0x3F;");
            sb.AppendLine("        int idx = 1 + pal * 4 + (color - 1);");
            sb.AppendLine("        return Palette[idx & 0x1F] & 0x3F;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static int GetPatternPixel(int patternBase, int tile, int px, int py)");
            sb.AppendLine("    {");
            sb.AppendLine("        int addr = patternBase + tile * 16 + py;");
            sb.AppendLine("        int addr2 = addr + 8;");
            sb.AppendLine("        byte low, high;");
            sb.AppendLine("        if (Runtime.ChrRom.Length > 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            int len = Runtime.ChrRom.Length;");
            sb.AppendLine("            addr = addr % len;");
            sb.AppendLine("            addr2 = addr2 % len;");
            sb.AppendLine("            low = Runtime.ChrRom[addr];");
            sb.AppendLine("            high = Runtime.ChrRom[addr2];");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            addr &= 0x1FFF;");
            sb.AppendLine("            addr2 = (addr + 8) & 0x1FFF;");
            sb.AppendLine("            low = VRam[addr];");
            sb.AppendLine("            high = VRam[addr2];");
            sb.AppendLine("        }");
            sb.AppendLine("        int bit = 7 - px;");
            sb.AppendLine("        return ((low >> bit) & 1) | (((high >> bit) & 1) << 1);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ================================================================
        // APU stub
        // ================================================================

        private void AppendApu(StringBuilder sb)
        {
            sb.AppendLine("static class Apu");
            sb.AppendLine("{");
            sb.AppendLine("    public static byte[] Regs = new byte[0x18];");
            sb.AppendLine();
            sb.AppendLine("    public static void Reset() { Array.Clear(Regs, 0, Regs.Length); }");
            sb.AppendLine();
            sb.AppendLine("    public static byte ReadReg(ushort addr)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (addr == 0x4016) return Runtime.JoyRead1();");
            sb.AppendLine("        if (addr == 0x4017) return Runtime.JoyRead2();");
            sb.AppendLine("        if (addr >= 0x4000 && addr <= 0x4017) return Regs[addr - 0x4000];");
            sb.AppendLine("        return 0;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void WriteReg(ushort addr, byte value)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (addr == 0x4016) { Runtime.JoyStrobe(value); Regs[addr - 0x4000] = value; return; }");
            sb.AppendLine("        if (addr >= 0x4000 && addr <= 0x4017) Regs[addr - 0x4000] = value;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ================================================================
        // Mapper stub
        // ================================================================

        private void AppendMapper(StringBuilder sb)
        {
            sb.AppendLine("static class MapperStub");
            sb.AppendLine("{");
            sb.AppendLine("    public static int PrgBank = 0;");
            sb.AppendLine("    public static void Reset() { PrgBank = 0; }");
            sb.AppendLine("    public static byte Read(ushort addr) { return 0x40; }");
            sb.AppendLine("    public static void Write(ushort addr, byte value)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (Runtime.Mapper == 2) { PrgBank = value & 0x0F; return; }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private void AppendForm(StringBuilder sb)
        {
            sb.AppendLine("class PpuForm : Form");
            sb.AppendLine("{");
            sb.AppendLine("    private System.Windows.Forms.Timer _timer;");
            sb.AppendLine("    private Bitmap _front;");
            sb.AppendLine("    private Bitmap _work;");
            sb.AppendLine("    private Thread _renderThread;");
            sb.AppendLine("    private volatile bool _closing;");
            sb.AppendLine();
            sb.AppendLine("    public PpuForm()");
            sb.AppendLine("    {");
            sb.AppendLine("        Text = \"NES Lifted: \" + Runtime.GameName;");
            sb.AppendLine("        ClientSize = new Size(256 * 2, 240 * 2);");
            sb.AppendLine("        FormBorderStyle = FormBorderStyle.FixedSingle;");
            sb.AppendLine("        MaximizeBox = false;");
            sb.AppendLine("        StartPosition = FormStartPosition.CenterScreen;");
            sb.AppendLine("        SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.UserPaint | ControlStyles.OptimizedDoubleBuffer, true);");
            sb.AppendLine();
            sb.AppendLine("        _front = new Bitmap(256, 240, PixelFormat.Format32bppArgb);");
            sb.AppendLine("        _work = new Bitmap(256, 240, PixelFormat.Format32bppArgb);");
            sb.AppendLine();
            sb.AppendLine("        _timer = new System.Windows.Forms.Timer();");
            sb.AppendLine("        _timer.Interval = 16;");
            sb.AppendLine("        _timer.Tick += delegate(object sender, EventArgs e)");
            sb.AppendLine("        {");
            sb.AppendLine("            Ppu.FrameCount++;");
            sb.AppendLine("            Ppu.Status = (byte)((Ppu.Status & 0xBF) | 0x80);");
            sb.AppendLine("            if ((Ppu.Ctrl & 0x80) != 0 && !Runtime.InNmi) Runtime.NmiPending = true;");
            sb.AppendLine("            Invalidate();");
            sb.AppendLine("        };");
            sb.AppendLine("        _timer.Start();");
            sb.AppendLine();
            sb.AppendLine("        _renderThread = new Thread(new ThreadStart(RenderLoop));");
            sb.AppendLine("        _renderThread.IsBackground = true;");
            sb.AppendLine("        _renderThread.Priority = ThreadPriority.BelowNormal;");
            sb.AppendLine("        _renderThread.Start();");
            sb.AppendLine();
            sb.AppendLine("        this.KeyPreview = true;");
            sb.AppendLine("        this.KeyDown += delegate(object s, KeyEventArgs ke) { SetJoyKey(ke.KeyCode, true); ke.SuppressKeyPress = true; };");
            sb.AppendLine("        this.KeyUp += delegate(object s, KeyEventArgs ke) { SetJoyKey(ke.KeyCode, false); };");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    void RenderLoop()");
            sb.AppendLine("    {");
            sb.AppendLine("        while (!_closing)");
            sb.AppendLine("        {");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                Ppu.RenderScreen();");
            sb.AppendLine("                BlitTo(_work);");
            sb.AppendLine("                DrawOsd(_work);");
            sb.AppendLine("                Bitmap ready = _work;");
            sb.AppendLine("                _work = Interlocked.Exchange(ref _front, ready);");
            sb.AppendLine("                Thread.Sleep(4);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch { try { Thread.Sleep(16); } catch { } }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    void BlitTo(Bitmap bmp)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (bmp == null) return;");
            sb.AppendLine("        Rectangle rc = new Rectangle(0, 0, 256, 240);");
            sb.AppendLine("        BitmapData data = bmp.LockBits(rc, ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            if (data.Stride == 256 * 4) Marshal.Copy(Ppu.Screen, 0, data.Scan0, Ppu.Screen.Length);");
            sb.AppendLine("            else for (int y = 0; y < 240; y++) { IntPtr dst = new IntPtr(data.Scan0.ToInt64() + y * data.Stride); Marshal.Copy(Ppu.Screen, y * 256 * 4, dst, 256 * 4); }");
            sb.AppendLine("        }");
            sb.AppendLine("        finally { bmp.UnlockBits(data); }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    void DrawOsd(Bitmap bmp)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (bmp == null) return;");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            using (Graphics g = Graphics.FromImage(bmp))");
            sb.AppendLine("            {");
            sb.AppendLine("                string c = string.Format(\"F:{0} I:{1} T:{2}\", Ppu.FrameCount, Runtime.InsCount, Runtime.TrapCount);");
            sb.AppendLine("                g.FillRectangle(Brushes.Black, 0, 0, 256, 15);");
            sb.AppendLine("                g.DrawString(c, SystemFonts.DefaultFont, Brushes.Yellow, 2, 1);");
            sb.AppendLine("                if (!string.IsNullOrEmpty(Runtime.LastError))");
            sb.AppendLine("                {");
            sb.AppendLine("                    string msg = Runtime.LastError; if (msg.Length > 56) msg = msg.Substring(0, 56);");
            sb.AppendLine("                    g.FillRectangle(Brushes.Black, 0, 222, 256, 18);");
            sb.AppendLine("                    g.DrawString(msg, SystemFonts.DefaultFont, Brushes.Red, 2, 224);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        catch { }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    protected override void OnPaint(PaintEventArgs e)");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnPaint(e);");
            sb.AppendLine("        Bitmap b = Volatile.Read(ref _front);");
            sb.AppendLine("        if (b != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            e.Graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.NearestNeighbor;");
            sb.AppendLine("            e.Graphics.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.Half;");
            sb.AppendLine("            e.Graphics.DrawImage(b, 0, 0, ClientSize.Width, ClientSize.Height);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static void SetJoyKey(Keys k, bool down)");
            sb.AppendLine("    {");
            sb.AppendLine("        int b = KeyBit(k); if (b < 0) return;");
            sb.AppendLine("        if (down) Runtime.Joy1Buttons = (byte)(Runtime.Joy1Buttons | (1 << b));");
            sb.AppendLine("        else Runtime.Joy1Buttons = (byte)(Runtime.Joy1Buttons & ~(1 << b));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    static int KeyBit(Keys k)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (k)");
            sb.AppendLine("        {");
            sb.AppendLine("            case Keys.X: return 0;");
            sb.AppendLine("            case Keys.Z: return 1;");
            sb.AppendLine("            case Keys.Back: case Keys.ShiftKey: case Keys.LShiftKey: case Keys.RShiftKey: return 2;");
            sb.AppendLine("            case Keys.Enter: return 3;");
            sb.AppendLine("            case Keys.Up: return 4;");
            sb.AppendLine("            case Keys.Down: return 5;");
            sb.AppendLine("            case Keys.Left: return 6;");
            sb.AppendLine("            case Keys.Right: return 7;");
            sb.AppendLine("            default: return -1;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    protected override void OnFormClosing(FormClosingEventArgs e)");
            sb.AppendLine("    {");
            sb.AppendLine("        _closing = true;");
            sb.AppendLine("        if (_renderThread != null && _renderThread.IsAlive) _renderThread.Join(500);");
            sb.AppendLine("        base.OnFormClosing(e);");
            sb.AppendLine("        _timer.Stop();");
            sb.AppendLine("        if (_front != null) { _front.Dispose(); _front = null; }");
            sb.AppendLine("        if (_work != null) { _work.Dispose(); _work = null; }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ================================================================
        // Instruction emission
        // ================================================================

        private void EmitInstruction(StringBuilder sb, Instruction inst)
        {
            if (inst.Control == OpControl.Invalid)
            {
                Line(sb, "Runtime.UnknownOpcode(0x" + inst.Opcode.ToString("X2") + ", 0x" + inst.Address.ToString("X4") + ");");
                EmitGoto(sb, inst.Fallthrough);
                return;
            }

            switch (inst.Control)
            {
                case OpControl.Branch: EmitBranch(sb, inst); return;
                case OpControl.Jmp: EmitGoto(sb, inst.Target); return;
                case OpControl.JmpInd: EmitIndirectJump(sb, inst); return;
                case OpControl.Jsr: EmitJsr(sb, inst); return;
                case OpControl.Rts: EmitRts(sb); return;
                case OpControl.Rti: EmitRti(sb); return;
                case OpControl.Brk: EmitBrk(sb, inst); return;
            }

            EmitOperation(sb, inst);

            if (inst.Info != null && inst.Info.Mn == "KIL")
                return;

            EmitGoto(sb, inst.Fallthrough);
        }

        private void EmitBranch(StringBuilder sb, Instruction inst)
        {
            string cond = GetBranchCondition(inst.Info.Mn);
            Line(sb, "if (" + cond + ")");
            Line(sb, "{");
            if (_labels.ContainsKey(inst.Target))
                EmitGoto(sb, inst.Target);
            else
            {
                Line(sb, "Runtime.Trap(\"Missing branch target $" + inst.Target.ToString("X4") + "\");");
                EmitGoto(sb, inst.Fallthrough);
            }
            Line(sb, "}");
            Line(sb, "else");
            Line(sb, "{");
            EmitGoto(sb, inst.Fallthrough);
            Line(sb, "}");
        }

        private void EmitJsr(StringBuilder sb, Instruction inst)
        {
            Line(sb, "Runtime.JsrPush(0x" + inst.Fallthrough.ToString("X4") + ");");
            EmitGoto(sb, inst.Target);
        }

        private void EmitRts(StringBuilder sb)
        {
            Line(sb, "Runtime.DispatchTarget = Runtime.RtsPull();");
            Line(sb, "goto Dispatch;");
        }

        private void EmitRti(StringBuilder sb)
        {
            Line(sb, "Runtime.P = (byte)((Runtime.Pull() & 0xEF) | 0x20);");
            Line(sb, "Runtime.DispatchTarget = Runtime.Pull16();");
            Line(sb, "Runtime.InNmi = false;");
            Line(sb, "goto Dispatch;");
        }

        private void EmitBrk(StringBuilder sb, Instruction inst)
        {
            ushort pcPlus2 = (ushort)(inst.Address + 2);
            Line(sb, "Runtime.Push16(0x" + pcPlus2.ToString("X4") + ");");
            Line(sb, "Runtime.Push((byte)(Runtime.P | 0x30));");
            Line(sb, "Runtime.P = (byte)(Runtime.P | 0x04);");
            Line(sb, "Runtime.DispatchTarget = Memory.Read16(0xFFFE);");
            Line(sb, "goto Dispatch;");
        }

        private void EmitIndirectJump(StringBuilder sb, Instruction inst)
        {
            ushort ptr = inst.Operand;
            ushort loAddr = ptr;
            ushort hiAddr = (ushort)((ptr & 0xFF00) | ((ptr + 1) & 0x00FF));
            Line(sb, "Runtime.DispatchTarget = (ushort)(Memory.Read(0x" + loAddr.ToString("X4") + ") | (Memory.Read(0x" + hiAddr.ToString("X4") + ") << 8));");
            Line(sb, "goto Dispatch;");
        }

        private void EmitGoto(StringBuilder sb, ushort addr)
        {
            if (_labels.ContainsKey(addr))
            {
                Line(sb, "goto L" + addr.ToString("X4") + ";");
            }
            else
            {
                Line(sb, "Runtime.DispatchTarget = 0x" + addr.ToString("X4") + ";");
                Line(sb, "goto Dispatch;");
            }
        }

        private void EmitOperation(StringBuilder sb, Instruction inst)
        {
            if (inst.Info == null)
            {
                Line(sb, "Runtime.UnknownOpcode(0x" + inst.Opcode.ToString("X2") + ", 0x" + inst.Address.ToString("X4") + ");");
                return;
            }

            string mn = inst.Info.Mn;
            AddrMode mode = inst.Info.Mode;
            string read = GetReadExpr(inst);
            string addrExpr = GetAddressExpr(inst);

            switch (mn)
            {
                case "LDA": Line(sb, "Runtime.A = " + read + "; Runtime.SetNZ(Runtime.A);"); break;
                case "LDX": Line(sb, "Runtime.X = " + read + "; Runtime.SetNZ(Runtime.X);"); break;
                case "LDY": Line(sb, "Runtime.Y = " + read + "; Runtime.SetNZ(Runtime.Y);"); break;
                case "STA": Line(sb, "Memory.Write(" + addrExpr + ", Runtime.A);"); break;
                case "STX": Line(sb, "Memory.Write(" + addrExpr + ", Runtime.X);"); break;
                case "STY": Line(sb, "Memory.Write(" + addrExpr + ", Runtime.Y);"); break;
                case "TAX": Line(sb, "Runtime.X = Runtime.A; Runtime.SetNZ(Runtime.X);"); break;
                case "TAY": Line(sb, "Runtime.Y = Runtime.A; Runtime.SetNZ(Runtime.Y);"); break;
                case "TXA": Line(sb, "Runtime.A = Runtime.X; Runtime.SetNZ(Runtime.A);"); break;
                case "TYA": Line(sb, "Runtime.A = Runtime.Y; Runtime.SetNZ(Runtime.A);"); break;
                case "TXS": Line(sb, "Runtime.SP = Runtime.X;"); break;
                case "TSX": Line(sb, "Runtime.X = Runtime.SP; Runtime.SetNZ(Runtime.X);"); break;
                case "INX": Line(sb, "Runtime.X = (byte)(Runtime.X + 1); Runtime.SetNZ(Runtime.X);"); break;
                case "INY": Line(sb, "Runtime.Y = (byte)(Runtime.Y + 1); Runtime.SetNZ(Runtime.Y);"); break;
                case "DEX": Line(sb, "Runtime.X = (byte)(Runtime.X - 1); Runtime.SetNZ(Runtime.X);"); break;
                case "DEY": Line(sb, "Runtime.Y = (byte)(Runtime.Y - 1); Runtime.SetNZ(Runtime.Y);"); break;
                case "ADC": Line(sb, "Runtime.Adc(" + read + ");"); break;
                case "SBC": Line(sb, "Runtime.Sbc(" + read + ");"); break;
                case "CMP": Line(sb, "Runtime.Compare(Runtime.A, " + read + ");"); break;
                case "CPX": Line(sb, "Runtime.Compare(Runtime.X, " + read + ");"); break;
                case "CPY": Line(sb, "Runtime.Compare(Runtime.Y, " + read + ");"); break;
                case "AND": Line(sb, "Runtime.A = (byte)(Runtime.A & " + read + "); Runtime.SetNZ(Runtime.A);"); break;
                case "ORA": Line(sb, "Runtime.A = (byte)(Runtime.A | " + read + "); Runtime.SetNZ(Runtime.A);"); break;
                case "EOR": Line(sb, "Runtime.A = (byte)(Runtime.A ^ " + read + "); Runtime.SetNZ(Runtime.A);"); break;
                case "BIT": Line(sb, "Runtime.Bit(" + read + ");"); break;
                case "ASL":
                    if (mode == AddrMode.Acc) Line(sb, "Runtime.A = Runtime.Asl(Runtime.A);");
                    else EmitRmw(sb, addrExpr, "Asl");
                    break;
                case "LSR":
                    if (mode == AddrMode.Acc) Line(sb, "Runtime.A = Runtime.Lsr(Runtime.A);");
                    else EmitRmw(sb, addrExpr, "Lsr");
                    break;
                case "ROL":
                    if (mode == AddrMode.Acc) Line(sb, "Runtime.A = Runtime.Rol(Runtime.A);");
                    else EmitRmw(sb, addrExpr, "Rol");
                    break;
                case "ROR":
                    if (mode == AddrMode.Acc) Line(sb, "Runtime.A = Runtime.Ror(Runtime.A);");
                    else EmitRmw(sb, addrExpr, "Ror");
                    break;
                case "INC": EmitIncDec(sb, addrExpr, true); break;
                case "DEC": EmitIncDec(sb, addrExpr, false); break;
                case "CLC": Line(sb, "Runtime.P = (byte)(Runtime.P & 0xFE);"); break;
                case "SEC": Line(sb, "Runtime.P = (byte)(Runtime.P | 0x01);"); break;
                case "CLI": Line(sb, "Runtime.P = (byte)(Runtime.P & 0xFB);"); break;
                case "SEI": Line(sb, "Runtime.P = (byte)(Runtime.P | 0x04);"); break;
                case "CLV": Line(sb, "Runtime.P = (byte)(Runtime.P & 0xBF);"); break;
                case "CLD": Line(sb, "Runtime.P = (byte)(Runtime.P & 0xF7);"); break;
                case "SED": Line(sb, "Runtime.P = (byte)(Runtime.P | 0x08);"); break;
                case "PHA": Line(sb, "Runtime.Push(Runtime.A);"); break;
                case "PLA": Line(sb, "Runtime.A = Runtime.Pull(); Runtime.SetNZ(Runtime.A);"); break;
                case "PHP": Line(sb, "Runtime.Push((byte)(Runtime.P | 0x30));"); break;
                case "PLP": Line(sb, "Runtime.P = (byte)((Runtime.Pull() & 0xEF) | 0x20);"); break;
                case "NOP": break;
                case "LAX": Line(sb, "Runtime.A = Runtime.X = " + read + "; Runtime.SetNZ(Runtime.A);"); break;
                case "SAX": Line(sb, "Memory.Write(" + addrExpr + ", (byte)(Runtime.A & Runtime.X));"); break;
                case "DCP":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = (byte)(Memory.Read(rmw) - 1);");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.Compare(Runtime.A, tmp);");
                    break;
                case "ISB":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = (byte)(Memory.Read(rmw) + 1);");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.Sbc(tmp);");
                    break;
                case "SLO":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = Runtime.Asl(Memory.Read(rmw));");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.A = (byte)(Runtime.A | tmp); Runtime.SetNZ(Runtime.A);");
                    break;
                case "RLA":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = Runtime.Rol(Memory.Read(rmw));");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.A = (byte)(Runtime.A & tmp); Runtime.SetNZ(Runtime.A);");
                    break;
                case "SRE":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = Runtime.Lsr(Memory.Read(rmw));");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.A = (byte)(Runtime.A ^ tmp); Runtime.SetNZ(Runtime.A);");
                    break;
                case "RRA":
                    Line(sb, "ushort rmw = " + addrExpr + ";");
                    Line(sb, "byte tmp = Runtime.Ror(Memory.Read(rmw));");
                    Line(sb, "Memory.Write(rmw, tmp);");
                    Line(sb, "Runtime.Adc(tmp);");
                    break;
                case "AXA": Line(sb, "Memory.Write(" + addrExpr + ", (byte)(Runtime.A & Runtime.X));"); break;
                case "KIL": Line(sb, "Runtime.Trap(\"KIL/HLT opcode executed\"); return;"); break;
                case "ANC": Line(sb, "Runtime.A = (byte)(Runtime.A & " + read + "); Runtime.SetCarry((Runtime.A & 0x80) != 0); Runtime.SetNZ(Runtime.A);"); break;
                case "ALR": Line(sb, "Runtime.A = Runtime.Lsr((byte)(Runtime.A & " + read + "));"); break;
                case "ARR": Line(sb, "Runtime.A = Runtime.Ror((byte)(Runtime.A & " + read + "));"); break;
                case "ANE": Line(sb, "Runtime.A = (byte)((Runtime.A | 0xEE) & Runtime.X & " + read + "); Runtime.SetNZ(Runtime.A);"); break;
                case "LXA": Line(sb, "Runtime.A = (byte)((Runtime.A | 0xEE) & " + read + "); Runtime.X = Runtime.A; Runtime.SetNZ(Runtime.A);"); break;
                case "AXS": Line(sb, "{ int axs = (Runtime.A & Runtime.X) - " + read + "; Runtime.X = (byte)axs; Runtime.SetCarry(axs >= 0); Runtime.SetNZ(Runtime.X); }"); break;
                case "SHY": Line(sb, "Memory.Write(" + addrExpr + ", Runtime.Y);"); break;
                case "LAS": Line(sb, "Runtime.SP = (byte)(Runtime.SP & " + read + "); Runtime.A = Runtime.SP; Runtime.X = Runtime.SP; Runtime.SetNZ(Runtime.SP);"); break;
                default:
                    Line(sb, "Runtime.UnknownOpcode(0x" + inst.Opcode.ToString("X2") + ", 0x" + inst.Address.ToString("X4") + ");");
                    break;
            }
        }

        private void EmitRmw(StringBuilder sb, string addrExpr, string helper)
        {
            Line(sb, "ushort rmw = " + addrExpr + ";");
            Line(sb, "byte tmp = Memory.Read(rmw);");
            Line(sb, "tmp = Runtime." + helper + "(tmp);");
            Line(sb, "Memory.Write(rmw, tmp);");
        }

        private void EmitIncDec(StringBuilder sb, string addrExpr, bool inc)
        {
            Line(sb, "ushort rmw = " + addrExpr + ";");
            if (inc) Line(sb, "byte tmp = (byte)(Memory.Read(rmw) + 1);");
            else Line(sb, "byte tmp = (byte)(Memory.Read(rmw) - 1);");
            Line(sb, "Runtime.SetNZ(tmp);");
            Line(sb, "Memory.Write(rmw, tmp);");
        }

        // ================================================================
        // Helpers
        // ================================================================

        private string GetBranchCondition(string mn)
        {
            switch (mn)
            {
                case "BPL": return "(Runtime.P & 0x80) == 0";
                case "BMI": return "(Runtime.P & 0x80) != 0";
                case "BVC": return "(Runtime.P & 0x40) == 0";
                case "BVS": return "(Runtime.P & 0x40) != 0";
                case "BCC": return "(Runtime.P & 0x01) == 0";
                case "BCS": return "(Runtime.P & 0x01) != 0";
                case "BNE": return "(Runtime.P & 0x02) == 0";
                case "BEQ": return "(Runtime.P & 0x02) != 0";
                default: return "true";
            }
        }

        private string GetReadExpr(Instruction inst)
        {
            switch (inst.Info.Mode)
            {
                case AddrMode.Imm: return "0x" + inst.Operand.ToString("X2");
                case AddrMode.Acc: return "Runtime.A";
                case AddrMode.Imp: return "0";
                default: return "Memory.Read(" + GetAddressExpr(inst) + ")";
            }
        }

        private string GetAddressExpr(Instruction inst)
        {
            string op2 = inst.Operand.ToString("X2");
            string op4 = inst.Operand.ToString("X4");

            switch (inst.Info.Mode)
            {
                case AddrMode.Zp: return "0x" + op2;
                case AddrMode.ZpX: return "(ushort)((0x" + op2 + " + Runtime.X) & 0xFF)";
                case AddrMode.ZpY: return "(ushort)((0x" + op2 + " + Runtime.Y) & 0xFF)";
                case AddrMode.Abs: return "0x" + op4;
                case AddrMode.AbsX: return "unchecked((ushort)(0x" + op4 + " + Runtime.X))";
                case AddrMode.AbsY: return "unchecked((ushort)(0x" + op4 + " + Runtime.Y))";
                case AddrMode.XInd: return "Runtime.AddrXInd(0x" + op2 + ")";
                case AddrMode.IndY: return "Runtime.AddrIndY(0x" + op2 + ")";
                default: return "0";
            }
        }

        private int MnemIdFor(OpInfo info)
        {
            if (info == null) return 0;

            switch (info.Ctrl)
            {
                case OpControl.Jmp: return 44;
                case OpControl.JmpInd: return 44;
                case OpControl.Jsr: return 45;
                case OpControl.Rts: return 46;
                case OpControl.Rti: return 47;
                case OpControl.Brk: return 48;
                case OpControl.Branch: return 49;
                case OpControl.Invalid: return 0;
            }

            switch (info.Mn)
            {
                case "LDA": return 1;
                case "LDX": return 2;
                case "LDY": return 3;
                case "STA": return 4;
                case "STX": return 5;
                case "STY": return 6;
                case "TAX": return 7;
                case "TAY": return 8;
                case "TXA": return 9;
                case "TYA": return 10;
                case "TXS": return 11;
                case "TSX": return 12;
                case "INX": return 13;
                case "INY": return 14;
                case "DEX": return 15;
                case "DEY": return 16;
                case "ADC": return 17;
                case "SBC": return 18;
                case "CMP": return 19;
                case "CPX": return 20;
                case "CPY": return 21;
                case "AND": return 22;
                case "ORA": return 23;
                case "EOR": return 24;
                case "BIT": return 25;
                case "ASL": return 26;
                case "LSR": return 27;
                case "ROL": return 28;
                case "ROR": return 29;
                case "INC": return 30;
                case "DEC": return 31;
                case "CLC": return 32;
                case "SEC": return 33;
                case "CLI": return 34;
                case "SEI": return 35;
                case "CLV": return 36;
                case "CLD": return 37;
                case "SED": return 38;
                case "PHA": return 39;
                case "PLA": return 40;
                case "PHP": return 41;
                case "PLP": return 42;
                case "NOP": return 43;
                case "LAX": return 50;
                case "SAX": return 51;
                case "DCP": return 52;
                case "ISB": return 53;
                case "SLO": return 54;
                case "RLA": return 55;
                case "SRE": return 56;
                case "RRA": return 57;
                case "ANC": return 58;
                case "ALR": return 59;
                case "ARR": return 60;
                case "ANE": return 61;
                case "LXA": return 62;
                case "AXS": return 63;
                case "SHY": return 64;
                case "LAS": return 65;
                case "AXA": return 66;
                case "KIL": return 67;
                default: return 0;
            }
        }

        private void AppendByteArrayField(StringBuilder sb, string name, byte[] data)
        {
            if (data == null || data.Length == 0)
            {
                sb.AppendLine("public static readonly byte[] " + name + " = new byte[0];");
                return;
            }

            sb.AppendLine("public static readonly byte[] " + name + " = new byte[] {");

            int chunk = 16;
            for (int i = 0; i < data.Length; i += chunk)
            {
                sb.Append("    ");
                int end = Math.Min(i + chunk, data.Length);
                for (int j = i; j < end; j++)
                {
                    sb.Append("0x" + data[j].ToString("X2"));
                    if (j < data.Length - 1)
                        sb.Append(", ");
                }
                sb.AppendLine();
            }

            sb.AppendLine("};");
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "Game";

            StringBuilder sb = new StringBuilder();

            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            if (sb.Length == 0)
                sb.Append("Game");

            if (char.IsDigit(sb[0]))
                sb.Insert(0, '_');

            return "Game_" + sb.ToString();
        }

        private static void Line(StringBuilder sb, string text)
        {
            sb.AppendLine("            " + text);
        }
    }
}